services:
  mysql:
    image: mysql:8.0
    volumes: 
      - ./MySQL/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ROOT_USER_EMAIL: ${ROOT_USER_EMAIL}
      ROOT_USER_PASS: ${ROOT_USER_PASS}
      ROOT_USER_FNAME: ${ROOT_USER_FNAME}
      ROOT_USER_LNAME: ${ROOT_USER_LNAME}
      ROOT_USER_DOB: ${ROOT_USER_DOB}
      ROOT_USER_FIRST_QUESTION: ${ROOT_USER_FIRST_QUESTION}
      ROOT_USER_FIRST_ANSWER: ${ROOT_USER_FIRST_ANSWER}
      ROOT_USER_SECOND_QUESTION: ${ROOT_USER_SECOND_QUESTION}
      ROOT_USER_SECOND_ANSWER: ${ROOT_USER_SECOND_ANSWER}
      ROOT_USER_RECOVERY_PHONE: ${ROOT_USER_RECOVERY_PHONE}
      ROOT_USER_RECOVERY_EMAIL: ${ROOT_USER_RECOVERY_EMAIL}
    ports: 
      - 3306:3306
  mysql-session:
    image: mariadb:10.7
    container_name: mysql-session
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./Session/:/docker-entrypoint-initdb.d
      - mysql-session-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "SELECT 1",
          "|",
          "mariadb",
          '"-p$${MARIADB_ROOT_PASSWORD}"',
        ]
      interval: 20s
      timeout: 5s
      retries: 5

networks:
  database-network:

volumes:
  mysql-data:
  mysql-session-data:
